
spring:

  datasource:
    url: jdbc:mysql://172.17.0.3:3306/commerce?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234qwer
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-commerce

  jpa:
    hibernate:
      ddl-auto: none

  redis:
    host: 172.17.0.4
    port: 6379

# 로깅 설정
logging:
  level:
    com.ebuild.commerce: INFO
    org.springframework.web: INFO
