
spring:

  application:
    name: e-commerce-platform

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/commerce?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 10
#      minimum-idle: 10
#      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      data-source-properties:
        rewriteBatchedStatements: true
      pool-name: pool-commerce

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        #        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true

  # Security OAuth
  security:
    oauth2.client:
      registration:
        kakao:
          clientId: 51e9697725714014f504371c15a4b733
          clientSecret: 5AH9bxGyWIvrZXCaY7dN3N7XPDbBrgLQ
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider 설정
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id

  mvc:
    log-request-details: true

  jackson:
    serialization:
      fail-on-empty-beans: false

# 로깅 설정
logging:
  level:
    com.ebuild.commerce: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

# JWT 토큰 설정
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

# cors 설정
cors:
  allowed-origins: 'http://localhost:8080'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth/redirect
