
spring:

  application:
    name: programmers spring assignments

  jpa:
    open-in-view : false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      generate-ddl: true
      hibernate:
#        use_sql_comments: true
        format_sql: true
        show_sql: true

  mvc:
    log-request-details: true

  jackson:
    serialization:
      fail-on-empty-beans: false

logging.level:
  org.hibernate.SQL: debug
