
spring:

#  datasource:
#    url: jdbc:mysql://172.30.1.31:3306/commerce?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
#    username: root
#    password: 1234qwer
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      auto-commit: false
#      connection-test-query: SELECT 1
#      minimum-idle: 10
#      maximum-pool-size: 50
#      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
#      pool-name: pool-commerce

  jpa:
    hibernate:
      ddl-auto: create

  redis:
    host: 172.30.1.31
    port: 6379